// app/routes/login.tsx
import LogoSmall from "~/components/logo_small";
import { Form, Link, useActionData } from "@remix-run/react";
import type { ActionArgs } from "@remix-run/node";
import { createUserSession } from "~/utils/session";
import { LoginUser } from "~/controllers/auth.server";
import { badRequest } from "~/utils/request";

export const action = async ({ request }: ActionArgs) => {
    const body = await request.formData();
    const credentials = Object.fromEntries(body);

    try {
        const user = await LoginUser(credentials);
        return createUserSession(user.id, '/dashboard');
    } catch (error) {
        // TODO Log error
    }

    return badRequest({
        formError: 'Invalid credentials. Please check email and password.',
    });
};

export default function Login() {
    const actionData = useActionData<typeof action>();

    return (
        <div className="page page-center">
            <div className="container-tight py-4">
                <div className="text-center mb-4">
                    <LogoSmall />
                </div>

                { actionData?.formError ? (
                    <div className="alert alert-danger" role="alert">
                        <div className="text-muted">{ actionData.formError }</div>
                    </div>
                ) : null }

                <Form className="card card-md" autoComplete="off" method="post">
                    {/* @csrf */}
                    {/* <x-honeypot wire:model="extraFields" /> */}

                    <div className="card-body">
                        <h2 className="card-title text-center mb-4">Login</h2>
                        <div className="mb-3">
                            <label className="form-label">Email address</label>
                            <input type="email" name="email" className="form-control" placeholder="Enter email" />
                        </div>
                        <div className="mb-2">
                            <label className="form-label">
                                Password
                                {/* <span className="form-label-description">
                                    <a href="">I forgot password</a>
                                </span> */}
                            </label>
                            <div className="mb-3">
                                <input type="password" name="password" className="form-control" placeholder="Password" autoComplete="off" />
                            </div>
                        </div>
                        <div className="form-footer">
                            <button type="submit" className="btn btn-primary w-100">Sign in</button>
                        </div>
                    </div>
                </Form>
                <div className="text-center text-muted mt-3">
                    Don't have account yet? Enroll in <Link to="/preview">closed preview</Link>
                </div>
            </div>
        </div>
    );
}

// src/routes/login/+page.svelte
<script lang="ts">
	import logo from '$lib/images/logo.svg';
	import type { PageData, ActionData } from './$types';
	import { enhance } from '$app/forms';

	export let data: PageData;
	export let form: ActionData;
</script>

<div class="page page-center">
	<div class="container container-tight py-4">
		<div class="text-center mb-4">
			<a href="." class="navbar-brand navbar-brand-autodark">
				<img src={logo} alt="" height="100" />
			</a>
		</div>

		<!-- Success alert -->
		{#if data.flashMessage}
			<div class="alert alert-success" role="alert">
				<div class="text-muted">{data.flashMessage.message}</div>
			</div>
		{/if}

		<!-- Error alert -->
		{#if form?.error}
			<div class="alert alert-danger" role="alert">
				<div class="text-muted">{form.error}</div>
			</div>
		{/if}

		<div class="card card-md">
			<div class="card-body">
				<h2 class="h2 text-center mb-4">Login to your account</h2>
				<form method="post" autocomplete="off" use:enhance>
					<div class="mb-3">
						<!-- svelte-ignore a11y-label-has-associated-control -->
						<label class="form-label required">Email</label>
						<input type="email" name="email" class="form-control" autocomplete="off" />
					</div>
					<div class="mb-2">
						<!-- svelte-ignore a11y-label-has-associated-control -->
						<label class="form-label required">
							Password
							<span class="form-label-description">
								<a href="/forgot-password">I forgot password</a>
							</span>
						</label>
						<div class="input-group input-group-flat">
							<input type="password" name="password" class="form-control" autocomplete="off" />
						</div>
					</div>
					<div class="form-footer">
						<button type="submit" class="btn btn-primary w-100">Sign in</button>
					</div>
				</form>
			</div>
		</div>
		<div class="text-center text-muted mt-3">
			Don't have account yet? Enroll in <a href="/preview" tabindex="-1">closed preview</a>
		</div>
	</div>
</div>
